# Bolus Advisor
# Shizuka Kamishima
title: Bolus Advisor
url: "http://bolus.vortalcord.net"
baseurl: ""
markdown: kramdown

gems:
  - jekyll-github-metadata

repository: shizuka/bolus-advisor

kramdown:
  input: GFM
  hard_wrap: false
  smart_quotes: ["apos", "apos", "quot", "quot"]

sass:
  sass_dir: _sass
